_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 51269c7b-1816-42c3-8ca1-c789015b07e3
name: 'Innoraft Employee Management System'
mail: admin@example.com
slogan: ''
page:
  403: /node/31
  404: /node/30
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: pinku.kumar@innoraft.com
